# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Pablo Acuña
tagline:          'Software Development'
description:      "A Chilean Software Developer's journey to find and document best practices and the latest in programming. Author of <a href='https://www.amazon.com/Deploying-Rails-Docker-Kubernetes-ECS/dp/1484224140'>Deploying Rails with Docker, Kubernetes and ECS</a>"
url:              http://pacuna.io
baseurl:          /pacuna.github.io

author:
  name:           'Pablo Acuña'
  url:            https://twitter.com/pabloacunar

gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pacuna

theme: jekyll-theme-minimal